<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="3.2.2" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../RaiDiagram.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../examples/ScheduleRehearsal/ScheduleRehearsal.raid"
			Link="Examples/ScheduleRehearsal/ScheduleRehearsal.raid"
			CopyToOutputDirectory="PreserveNewest" />
		<None Include="../examples/ScheduleRehearsal/ScheduleRehearsal.puml"
			Link="Examples/ScheduleRehearsal/ScheduleRehearsal.puml"
			CopyToOutputDirectory="PreserveNewest" />
		<None Include="../examples/ScheduleRehearsal/ScheduleRehearsal_config.puml"
			Link="Examples/ScheduleRehearsal/ScheduleRehearsal_config.puml"
			CopyToOutputDirectory="PreserveNewest" />
		<None Include="../examples/ScheduleRehearsal/ScheduleRehearsal.svg"
			Link="Examples/ScheduleRehearsal/ScheduleRehearsal.svg"
			CopyToOutputDirectory="PreserveNewest" />
		<None Include="../themes/puml-theme-raikeep-sketch.puml"
			Link="Themes/puml-theme-raikeep-sketch.puml"
			CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
